//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18052.
// 
#pragma warning disable 1591

namespace zfit.zfitService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="zfitWebMethodsSoap", Namespace="http://www.zfit.co.za/")]
    public partial class zfitWebMethods : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback zfitUserCallOperationCompleted;
        
        private System.Threading.SendOrPostCallback zfitFanCallOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public zfitWebMethods() {
            this.Url = global::zfit.Properties.Settings.Default.zfitConsumer_zfitService_zfitWebMethods;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event zfitUserCallCompletedEventHandler zfitUserCallCompleted;
        
        /// <remarks/>
        public event zfitFanCallCompletedEventHandler zfitFanCallCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.zfit.co.za/zfitUserCall", RequestNamespace="http://www.zfit.co.za/", ResponseNamespace="http://www.zfit.co.za/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string zfitUserCall(string aXmlCredentials, string aXmlArgument) {
            object[] results = this.Invoke("zfitUserCall", new object[] {
                        aXmlCredentials,
                        aXmlArgument});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void zfitUserCallAsync(string aXmlCredentials, string aXmlArgument) {
            this.zfitUserCallAsync(aXmlCredentials, aXmlArgument, null);
        }
        
        /// <remarks/>
        public void zfitUserCallAsync(string aXmlCredentials, string aXmlArgument, object userState) {
            if ((this.zfitUserCallOperationCompleted == null)) {
                this.zfitUserCallOperationCompleted = new System.Threading.SendOrPostCallback(this.OnzfitUserCallOperationCompleted);
            }
            this.InvokeAsync("zfitUserCall", new object[] {
                        aXmlCredentials,
                        aXmlArgument}, this.zfitUserCallOperationCompleted, userState);
        }
        
        private void OnzfitUserCallOperationCompleted(object arg) {
            if ((this.zfitUserCallCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.zfitUserCallCompleted(this, new zfitUserCallCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.zfit.co.za/zfitFanCall", RequestNamespace="http://www.zfit.co.za/", ResponseNamespace="http://www.zfit.co.za/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string zfitFanCall(string aXmlCredentials, string aXmlArgument) {
            object[] results = this.Invoke("zfitFanCall", new object[] {
                        aXmlCredentials,
                        aXmlArgument});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void zfitFanCallAsync(string aXmlCredentials, string aXmlArgument) {
            this.zfitFanCallAsync(aXmlCredentials, aXmlArgument, null);
        }
        
        /// <remarks/>
        public void zfitFanCallAsync(string aXmlCredentials, string aXmlArgument, object userState) {
            if ((this.zfitFanCallOperationCompleted == null)) {
                this.zfitFanCallOperationCompleted = new System.Threading.SendOrPostCallback(this.OnzfitFanCallOperationCompleted);
            }
            this.InvokeAsync("zfitFanCall", new object[] {
                        aXmlCredentials,
                        aXmlArgument}, this.zfitFanCallOperationCompleted, userState);
        }
        
        private void OnzfitFanCallOperationCompleted(object arg) {
            if ((this.zfitFanCallCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.zfitFanCallCompleted(this, new zfitFanCallCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void zfitUserCallCompletedEventHandler(object sender, zfitUserCallCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class zfitUserCallCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal zfitUserCallCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void zfitFanCallCompletedEventHandler(object sender, zfitFanCallCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class zfitFanCallCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal zfitFanCallCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591